<center><img src="https://i.imgur.com/zRrFdsf.png" width="700"></center>

In [1]:
#Importacion de pandas
import pandas as pd
# Obtención de la tabla de Excel sin encabezado
data = pd.read_excel('https://github.com/DiegoAntonio-web/PC2/blob/main/HDI%20(1).xlsx?raw=true', header=None)

# Seleccionar las filas 5, 6 y 7 como nuevo encabezado (índices 4, 5 y 6)
new_header = data.iloc[4:7]  # Filas 5, 6 y 7

# Eliminar las filas usadas como encabezado
data = data.drop(index=[4, 5, 6])

# Combinar las filas seleccionadas en un nuevo encabezado
data.columns = new_header.apply(lambda x: ' '.join(x.dropna().astype(str)), axis=0)

# Restablecer el índice
data.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data

,HDI rank,Country,Human Development Index (HDI) Value 2021,,Life expectancy at birth (years) 2021,,Expected years of schooling (years) 2021,a,Mean years of schooling (years) 2021,a,Gross national income (GNI) per capita (2017 PPP $) 2021,,GNI per capita rank minus HDI rank 2021,b,HDI rank 2020
0,Back,Table 1. Human Development Index and its compo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Eliminar las primeras 4 filas
data_1 = data.drop(index=[0, 1, 2, 3])

# Restablecer el índice
data.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data_1

,HDI rank,Country,Human Development Index (HDI) Value 2021,,Life expectancy at birth (years) 2021,,Expected years of schooling (years) 2021,a,Mean years of schooling (years) 2021,a,Gross national income (GNI) per capita (2017 PPP $) 2021,,GNI per capita rank minus HDI rank 2021,b,HDI rank 2020
4,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
6,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
7,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2
8,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Eliminacion de todas las filas que contengan valores NaN a excepcion de la segunda columna
data_2 = data_1[~(data_1.iloc[:, 2:].isna().all(axis=1) & data_1.iloc[:, 1].notna())]

data_2

,HDI rank,Country,Human Development Index (HDI) Value 2021,,Life expectancy at birth (years) 2021,,Expected years of schooling (years) 2021,a,Mean years of schooling (years) 2021,a,Gross national income (GNI) per capita (2017 PPP $) 2021,,GNI per capita rank minus HDI rank 2021,b,HDI rank 2020
5,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
6,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
7,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2
8,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4
9,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,NaN,World,0.732,NaN,71.365465,NaN,12.780907,NaN,8.617461,NaN,16752.082922,NaN,—,NaN,—
227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Eliminación de columnas que contienen NaN en la primera fila
data_2 = data_2.loc[:, data_2.iloc[0].notna()]

# Reiniciar el índice del DataFrame
data_2.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data_2

,HDI rank,Country,Human Development Index (HDI) Value 2021,Life expectancy at birth (years) 2021,Expected years of schooling (years) 2021,Mean years of schooling (years) 2021,Gross national income (GNI) per capita (2017 PPP $) 2021,GNI per capita rank minus HDI rank 2021,HDI rank 2020
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
215,NaN,World,0.732,71.365465,12.780907,8.617461,16752.082922,—,—
216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Eliminación de filas donde el primer elemento de la primera columna es NaN
data_2 = data_2.dropna(subset=[data_2.columns[0]], axis=0)

# Reiniciar el índice del DataFrame
data_2.reset_index(drop=True, inplace=True)
data_2

,HDI rank,Country,Human Development Index (HDI) Value 2021,Life expectancy at birth (years) 2021,Expected years of schooling (years) 2021,Mean years of schooling (years) 2021,Gross national income (GNI) per capita (2017 PPP $) 2021,GNI per capita rank minus HDI rank 2021,HDI rank 2020
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
186,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187
187,188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1,188
188,189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3,189
189,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190
190,191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1,191

In [6]:
data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 9 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   HDI rank                                                  191 non-null    object
 1   Country                                                   191 non-null    object
 2   Human Development Index (HDI)  Value 2021                 191 non-null    object
 3   Life expectancy at birth (years) 2021                     191 non-null    object
 4   Expected years of schooling (years) 2021                  191 non-null    object
 5   Mean years of schooling (years) 2021                      191 non-null    object
 6   Gross national income (GNI) per capita (2017 PPP $) 2021  191 non-null    object
 7   GNI per capita rank minus HDI rank 2021                   191 non-null    object
 8   HDI rank 2020                                             191 non-null    object
dtypes: object(9)
memory usage: 13.6+ KB

In [7]:
# Convertir las columnas de la 3 a la 7 a float64
for col in data_2.columns[2:7]:  # Índices de columna 2 a 6 (3 a 7)
    data_2[col] = pd.to_numeric(data_2[col], errors='coerce')  # Convertir a float64

# Verificar el resultado
data_2

<ipython-input-7-01d847c87520>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2[col] = pd.to_numeric(data_2[col], errors='coerce')  # Convertir a float64

,HDI rank,Country,Human Development Index (HDI) Value 2021,Life expectancy at birth (years) 2021,Expected years of schooling (years) 2021,Mean years of schooling (years) 2021,Gross national income (GNI) per capita (2017 PPP $) 2021,GNI per capita rank minus HDI rank 2021,HDI rank 2020
0,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,5,3
1,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,6,1
2,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,11,2
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,6,4
4,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,18,5
...,...,...,...,...,...,...,...,...,...
186,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187
187,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1,188
188,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3,189
189,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190
190,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1,191

In [8]:
data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 9 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   HDI rank                                                  191 non-null    object
 1   Country                                                   191 non-null    object
 2   Human Development Index (HDI)  Value 2021                 191 non-null    float64
 3   Life expectancy at birth (years) 2021                     191 non-null    float64
 4   Expected years of schooling (years) 2021                  191 non-null    float64
 5   Mean years of schooling (years) 2021                      191 non-null    float64
 6   Gross national income (GNI) per capita (2017 PPP $) 2021  191 non-null    float64
 7   GNI per capita rank minus HDI rank 2021                   191 non-null    object
 8   HDI rank 2020                                             191 non-null    object
dtypes: float64(5), object(4)
memory usage: 13.6+ KB

In [10]:
# Arreglamos el error de lectura de la columna 7, ya que el python lo leyo como "," 1,500 del excel, aca lo lee como 1500.0
# Dividir todos los elementos de la columna 7 entre 1000
data_2[data_2.columns[6]] = data_2[data_2.columns[6]] / 1000

# Verificar el resultado
data_2

<ipython-input-10-ddb7a34bea7b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2[data_2.columns[6]] = data_2[data_2.columns[6]] / 1000

,HDI rank,Country,Human Development Index (HDI) Value 2021,Life expectancy at birth (years) 2021,Expected years of schooling (years) 2021,Mean years of schooling (years) 2021,Gross national income (GNI) per capita (2017 PPP $) 2021,GNI per capita rank minus HDI rank 2021,HDI rank 2020
0,1,Switzerland,0.962,83.9872,16.500299,13.859660,66.933005,5,3
1,2,Norway,0.961,83.2339,18.185200,13.003630,64.660106,6,1
2,3,Iceland,0.959,82.6782,19.163059,13.767170,55.782050,11,2
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62.606845,6,4
4,5,Australia,0.951,84.5265,21.054590,12.726820,49.238433,18,5
...,...,...,...,...,...,...,...,...,...
186,187,Burundi,0.426,61.6627,10.722722,3.129267,0.731787,4,187
187,188,Central African Republic,0.404,53.8947,8.040172,4.334000,0.966059,1,188
188,189,Niger,0.400,61.5763,6.957112,2.116717,1.239867,-3,189
189,190,Chad,0.394,52.5254,8.035914,2.573774,1.364169,-7,190
190,191,South Sudan,0.385,54.9752,5.542510,5.726140,0.767787,-1,191